### PR TITLE
Removal of conversions, slight Server rework

### PR DESCRIPTION
**Pull request by tjkessler**
### 1.) The following conversions have been removed from ECNet:
- get_smiles
- smiles_to_descriptors
- smiles_to_mdl
- mdl_to_descriptors

*Note: these were adding clutter, and were not within the main scope of ECNet.

### 2.) PaDEL-Descriptor is no longer bundled into ECNet

*Note: with the removal of conversion functions, this is no longer needed.

### 3.) Database creation functions now rely on two separate packages:
- PaDELPy (https://github.com/ECRL/PaDELPy) - QSPR descriptor generation using PaDEL-Descriptor
- alvaDescPy (https://github.com/ECRL/alvaDescPy) - QSPR descriptor generation using alvaDesc

*Note: it made sense to create separate packages for interfacing with these software, a Python interface for generating QSPR descriptors is generally quite handy.

### 4.) _ecnet.tools.database.create_db_'s arguments have been changed:

```python
>>> ecnet.tools.database.create_db(['CC', 'CCC'], 'my_database.csv', targets=[13, 47])
```

Construct using alvaDesc:

```python
>>> ecnet.tools.database.create_db(['CC', 'CCC'], 'my_database.csv', targets=[13, 47], backend='alvadesc')
```

*Note: supplying SMILES strings and targets using lists makes more sense than requiring the user to create a separate file - this change allows the user to choose where the data comes from.

### 5.) _ecnet.tools.project.predict_'s arguments have been changed:
```python
>>> results = ecnet.tools.project.predict(['CC', 'CCC'], 'my_project.prj')
>>> print(results)
[[13], [47]]
```

*Note: similar to why we switched to lists as inputs in database creation, makes more sense

### 6.) _ecnet.Server_ has been rearranged a bit:
- project training has been moved to a separate function at _ecnet.tasks.training.train_project_
- various functions have been moved to _ecnet.utils.server_utils_:
    - creating a project folder structure
    - saving a project as a .prj file
    - opening a .prj file to use
- task-specific logging messages have been moved to their respective functions in _ecnet.tasks_

*Note: _ecnet.Server_ needed to be shrunk down, and functions that were obviously utilities were moved into utility files. This should also provide more direct access to the "back-end" of ECNet (subverting Server usage), allowing greater variation in experimental procedure.

### 7.) Added a suite of unit tests implemented with the _unittest_ library:
- in addition to Server unit tests, individual utilities of ECNet are tested
- added a Python script, _/tests/test_all.py_, to automatically run all unit tests and report a summary of successes/failures

*Note: it's time for "proper" unit testing, and that means implementing a unit testing package. I'm looking forward to expanding ECNet's tests and introduce more automation into the testing process.

### 8.) Installation now forces TensorFlow 1.13.1 to be installed

*Note: I've encountered _pip install tensorflow_ installing the 2.0.0 beta, which ECNet does not currently support - we'll make the change when we're ready (and so is Keras)

### 9.) Changed/added a variety of databases to the _/databases/_ directory
- All databases constructed using alvaDesc
- All SMILES strings have been validated with respect to compound name
    - PubChemPy (https://github.com/mcs07/PubChemPy) is a lifesaver
    - Compounds not found on PubChem were validated in-house by an ECRL research assistant

*Note: in order to ensure accurate QSPR-descriptor to experimental value correlation, accurate SMILES strings are necessary (assuming descriptors are being generated using them).

### CODE REVIEW

**Comment by tjkessler** [comment]
@hgromer Lots of changes here, let me know if anything needs further clarification

**Comment by tjkessler** [comment]
@hgromer,

The YAML error was likely caused by an installation of a previous release of PyYAML - with PyYAML 5.0+ the pyyaml.FullLoader is required to safely open .yaml files. To address this, and potential future dependency issues, I've forced specific versions for dependencies (https://github.com/ECRL/ECNet/pull/35/commits/f2a053b07f10bef2972e32a7ff5654929518250b).

Version 3.2.0 seems appropriate for the scale of this release.

**Comment by tjkessler** [comment]
@hgromer side note, I've been utilizing [Anaconda](https://www.anaconda.com/) for Python environment managing. Testing is much more robust when a new environment is created specifically for testing.

**Comment by hgromer** [comment]
> @hgromer side note, I've been utilizing [Anaconda](https://www.anaconda.com/) for Python environment managing. Testing is much more robust when a new environment is created specifically for testing.

I will definitely check that out. I feel that someone downloading this package off of pip should be able to immediately do a `python test_all.py` and be able to run and pass all the tests correctly.

**Comment by tjkessler** [comment]
> > @hgromer side note, I've been utilizing [Anaconda](https://www.anaconda.com/) for Python environment managing. Testing is much more robust when a new environment is created specifically for testing.
> 
> I will definitely check that out. I feel that someone downloading this package off of pip should be able to immediately do a `python test_all.py` and be able to run and pass all the tests correctly.

I couldn't agree more. Simulating a fresh installation of Python/ECNet ensures integrity of the package.

**Pull request merged**
